spring:
  application:
    name: curso_api
  datasource:
    url: jdbc:mysql://localhost:3306/curso_api?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


Esse é meu projeto em java
  Adicionar endpoints do curso
  Get all
  Get by id
  Delete by id
  Put
  Post
  Refatorar o service do instrutor para usar o mapstruct
  Remover o qualquer mapeamento manual ou função de mapeamento no InstrutorService
  Instrutor não precisa voltar com a lista de curso